//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdhocNotification
    {
        public AdhocNotification()
        {
            this.AdhocNotificationAcks = new HashSet<AdhocNotificationAck>();
        }
    
        public int Id { get; set; }
        public int SessionId { get; set; }
        public string Target { get; set; }
        public string Text { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual ICollection<AdhocNotificationAck> AdhocNotificationAcks { get; set; }
    }
}
