//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adjustment
    {
        public int SessionId { get; set; }
        public int Id { get; set; }
        public int AdjustmentTypeId { get; set; }
        public int NumericalType { get; set; }
        public double Value { get; set; }
        public string Reference { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
    
        public virtual AdjustmentType AdjustmentType { get; set; }
        public virtual Session Session { get; set; }
    }
}
