//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        public Batch()
        {
            this.Modify = false;
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public System.DateTime OrderTime { get; set; }
        public int RestaurantId { get; set; }
        public string Ident { get; set; }
        public bool Modify { get; set; }
        public Nullable<System.DateTime> SpoolTime { get; set; }
        public Nullable<System.DateTime> PrintedTime { get; set; }
        public int PrinterId { get; set; }
        public Nullable<bool> Printed { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
