//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlackMark
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string Reason { get; set; }
        public System.DateTime Added { get; set; }
        public System.DateTime Expires { get; set; }
    }
}
