//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashUpDay
    {
        public CashUpDay()
        {
            this.Sessions = new HashSet<Session>();
        }
    
        public int Id { get; set; }
        public int StaffId { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string Report { get; set; }
        public bool WrapUp { get; set; }
        public int RestaurantId { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual ICollection<Session> Sessions { get; set; }
    }
}
