//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckIn
    {
        public int Id { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        public virtual Diner Diner { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Party Party { get; set; }
    }
}
