//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Ratings = new HashSet<Rating>();
            this.BlackMarks = new HashSet<BlackMark>();
            this.DinerInstances = new HashSet<Diner>();
            this.Parties = new HashSet<Party>();
            this.AuthenticationKeys = new HashSet<AuthenticationKey>();
            this.CheckIns = new HashSet<CheckIn>();
            this.DietaryRequirements = new HashSet<DietaryRequirement>();
            this.FoodPreferences = new HashSet<FoodPreference>();
            this.Allergies = new HashSet<Allergy>();
            this.Name = new Name();
            this.Address = new NullableAddress();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string PhoneNumber { get; set; }
        public string Auth { get; set; }
        public string Salt { get; set; }
        public string Email { get; set; }
        public string FacebookId { get; set; }
        public string TwitterId { get; set; }
        public string FavouriteFood { get; set; }
        public string FavouriteDrink { get; set; }
        public string HatedFood { get; set; }
    
        public Name Name { get; set; }
        public NullableAddress Address { get; set; }
    
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<BlackMark> BlackMarks { get; set; }
        public virtual ICollection<Diner> DinerInstances { get; set; }
        public virtual ICollection<Party> Parties { get; set; }
        public virtual ICollection<AuthenticationKey> AuthenticationKeys { get; set; }
        public virtual ICollection<CheckIn> CheckIns { get; set; }
        public virtual ICollection<DietaryRequirement> DietaryRequirements { get; set; }
        public virtual ICollection<FoodPreference> FoodPreferences { get; set; }
        public virtual ICollection<Allergy> Allergies { get; set; }
    }
}
