//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diner
    {
        public Diner()
        {
            this.IsTable = false;
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SeatedSessionId { get; set; }
        public bool IsTable { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
