//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class epicuriContainer : DbContext
    {
        public epicuriContainer()
            : base("name=epicuriContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Restaurant> Restaurants { get; set; }
        public DbSet<Session> Sessions { get; set; }
        public DbSet<Service> Services { get; set; }
        public DbSet<Menu> Menus { get; set; }
        public DbSet<MenuCategory> MenuCategories { get; set; }
        public DbSet<MenuItem> MenuItems { get; set; }
        public DbSet<MenuTag> MenuTags { get; set; }
        public DbSet<MenuGroup> MenuGroups { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<Table> Tables { get; set; }
        public DbSet<Diner> Diners { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Rating> Ratings { get; set; }
        public DbSet<Floor> Floors { get; set; }
        public DbSet<Layout> Layouts { get; set; }
        public DbSet<Party> Parties { get; set; }
        public DbSet<Staff> Staffs { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Permission> Permissions { get; set; }
        public DbSet<ModifierGroup> ModifierGroups { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Currency> Currencies { get; set; }
        public DbSet<BlackMark> BlackMarks { get; set; }
        public DbSet<Device> Devices { get; set; }
        public DbSet<DeviceRegistrationToken> DeviceRegistrationTokens { get; set; }
        public DbSet<Resource> Resources { get; set; }
        public DbSet<ScheduleItem> ScheduleItems { get; set; }
        public DbSet<Notification> Notifications { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<RecurringScheduleItem> RecurringScheduleItems { get; set; }
        public DbSet<NotificationAck> NotificationAcks { get; set; }
        public DbSet<Course> Courses { get; set; }
        public DbSet<AdhocNotification> AdhocNotifications { get; set; }
        public DbSet<AdhocNotificationAck> AdhocNotificationAcks { get; set; }
        public DbSet<Batch> Batches { get; set; }
        public DbSet<AuthenticationKey> AuthenticationKeys { get; set; }
        public DbSet<TableLayout> TableLayouts { get; set; }
        public DbSet<CheckIn> CheckIns { get; set; }
        public DbSet<Payment> Payments { get; set; }
        public DbSet<Setting> Settings { get; set; }
        public DbSet<DefaultSetting> DefaultSettings { get; set; }
        public DbSet<DateConstraint> DateConstraints { get; set; }
        public DbSet<Printer> Printers { get; set; }
        public DbSet<FoodPreference> FoodPreferences { get; set; }
        public DbSet<Allergy> Allergies { get; set; }
        public DbSet<DietaryRequirement> DietaryRequirements { get; set; }
        public DbSet<CashUpDay> CashUpDay { get; set; }
        public DbSet<Adjustment> Adjustment { get; set; }
        public DbSet<AdjustmentType> AdjustmentTypes { get; set; }
        public DbSet<StaffAuthenticationKey> StaffAuthenticationKeys { get; set; }
        public DbSet<TaxType> TaxTypes { get; set; }
        public DbSet<Modifier> Modifiers { get; set; }
    }
}
