//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Floor
    {
        public Floor()
        {
            this.Scale = 1D;
            this.Deleted = false;
            this.Layouts = new HashSet<Layout>();
        }
    
        public int Id { get; set; }
        public int RestaurantId { get; set; }
        public string Name { get; set; }
        public short Capacity { get; set; }
        public int ResourceId { get; set; }
        public Nullable<int> LayoutId { get; set; }
        public double Scale { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        public virtual ICollection<Layout> Layouts { get; set; }
        public virtual Resource Resource { get; set; }
        public virtual Layout ActiveLayout { get; set; }
    }
}
