//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Layout
    {
        public Layout()
        {
            this.Temporary = false;
            this.Tables = new HashSet<TableLayout>();
        }
    
        public int Id { get; set; }
        public int FloorId { get; set; }
        public string Name { get; set; }
        public System.DateTime LastModified { get; set; }
        public bool Temporary { get; set; }
    
        public virtual Floor Floor { get; set; }
        public virtual ICollection<TableLayout> Tables { get; set; }
    }
}
