//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.Active = true;
            this.MenuCategories = new HashSet<MenuCategory>();
        }
    
        public int Id { get; set; }
        public string MenuName { get; set; }
        public int RestaurantId { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public bool Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual ICollection<MenuCategory> MenuCategories { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
