//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuGroup
    {
        public MenuGroup()
        {
            this.Order = 0;
            this.MenuItems = new HashSet<MenuItem>();
        }
    
        public int Id { get; set; }
        public int MenuCategoryId { get; set; }
        public string GroupName { get; set; }
        public int Order { get; set; }
    
        public virtual MenuCategory MenuCategory { get; set; }
        public virtual ICollection<MenuItem> MenuItems { get; set; }
    }
}
