//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuCategory
    {
        public MenuCategory()
        {
            this.Order = 0;
            this.Deleted = false;
            this.MenuGroups = new HashSet<MenuGroup>();
            this.Courses = new HashSet<Course>();
        }
    
        public int Id { get; set; }
        public int MenuId { get; set; }
        public string CategoryName { get; set; }
        public int Order { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual ICollection<MenuGroup> MenuGroups { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
    }
}
