//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public MenuItem()
        {
            this.Deleted = false;
            this.Unavailable = false;
            this.MenuTags = new HashSet<MenuTag>();
            this.MenuGroups = new HashSet<MenuGroup>();
            this.Ratings = new HashSet<Rating>();
            this.ModifierGroups = new HashSet<ModifierGroup>();
        }
    
        public int Id { get; set; }
        public int MenuGroupId { get; set; }
        public int TaxTypeId { get; set; }
        public int RestaurantId { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public string Description { get; set; }
        public string ImageURL { get; set; }
        public bool Deleted { get; set; }
        public int PrinterId { get; set; }
        public int MenuItemTypeId { get; set; }
        public bool Unavailable { get; set; }
    
        public virtual ICollection<MenuTag> MenuTags { get; set; }
        public virtual ICollection<MenuGroup> MenuGroups { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<ModifierGroup> ModifierGroups { get; set; }
        public virtual Printer Printer { get; set; }
        public virtual TaxType TaxType { get; set; }
    }
}
