//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modifier
    {
        public Modifier()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public int ModifierGroupId { get; set; }
        public string ModifierValue { get; set; }
        public double Cost { get; set; }
        public bool Deleted { get; set; }
        public int TaxType_Id { get; set; }
    
        public virtual ModifierGroup ModifierGroup { get; set; }
        public virtual TaxType TaxType { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
