//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModifierGroup
    {
        public ModifierGroup()
        {
            this.Deleted = false;
            this.Modifiers = new HashSet<Modifier>();
        }
    
        public int Id { get; set; }
        public string GroupName { get; set; }
        public int RestaurantId { get; set; }
        public short UpperLimit { get; set; }
        public bool Deleted { get; set; }
        public short LowerLimit { get; set; }
    
        public virtual ICollection<Modifier> Modifiers { get; set; }
    }
}
