//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public Notification()
        {
            this.NotificationAcks = new HashSet<NotificationAck>();
        }
    
        public int Id { get; set; }
        public string Text { get; set; }
        public string Target { get; set; }
        public int RestaurantId { get; set; }
    
        public virtual ICollection<NotificationAck> NotificationAcks { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
