//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationAck
    {
        public int Id { get; set; }
        public System.DateTime Time { get; set; }
        public int NotificationId { get; set; }
        public int SessionId { get; set; }
    
        public virtual Notification Notification { get; set; }
    }
}
