//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    
    public partial class NullableAddress
    {
        public string Street { get; set; }
        public string Town { get; set; }
        public string City { get; set; }
        public string PostCode { get; set; }
    }
}
