//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Party
    {
        public Party()
        {
            this.Deleted = false;
            this.CheckIn = new HashSet<CheckIn>();
        }
    
        public int Id { get; set; }
        public int RestaurantId { get; set; }
        public short NumberOfPeople { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public bool Deleted { get; set; }
        public int InstantiatedFromId { get; set; }
        public Nullable<System.DateTime> ArrivedTime { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        public virtual Customer LeadCustomer { get; set; }
        public virtual SeatedSession Session { get; set; }
        public virtual ICollection<CheckIn> CheckIn { get; set; }
    }
}
