//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Printer
    {
        public int Id { get; set; }
        public int RestaurantId { get; set; }
        public string Name { get; set; }
        public string IP { get; set; }
        public Nullable<int> RedirectPrinterId { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
    }
}
