//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecurringScheduleItem
    {
        public RecurringScheduleItem()
        {
            this.Notifications = new HashSet<Notification>();
        }
    
        public int Id { get; set; }
        public short InitialDelay { get; set; }
        public short Period { get; set; }
        public string Comment { get; set; }
        public int ServiceId { get; set; }
    
        public virtual ICollection<Notification> Notifications { get; set; }
    }
}
