//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation : Party
    {
        public Reservation()
        {
            this.Accepted = true;
        }
    
        public System.DateTime ReservationTime { get; set; }
        public string Notes { get; set; }
        public string Telephone { get; set; }
        public bool Accepted { get; set; }
        public bool Rejected { get; set; }
        public string RejectionNotice { get; set; }
    }
}
