//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public Resource()
        {
            this.RestaurantReceipts = new HashSet<Restaurant>();
        }
    
        public int Id { get; set; }
        public int RestaurantId { get; set; }
        public string CDNUrl { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        public virtual ICollection<Restaurant> RestaurantReceipts { get; set; }
    }
}
