//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public Restaurant()
        {
            this.Enabled = true;
            this.Sessions = new HashSet<Session>();
            this.Services = new HashSet<Service>();
            this.MenuTags = new HashSet<MenuTag>();
            this.MenuItems = new HashSet<MenuItem>();
            this.Floors = new HashSet<Floor>();
            this.Restaurants = new HashSet<Restaurant>();
            this.Devices = new HashSet<Device>();
            this.DeviceRegistrationTokens = new HashSet<DeviceRegistrationToken>();
            this.Resources = new HashSet<Resource>();
            this.Menus = new HashSet<Menu>();
            this.ModifierGroups = new HashSet<ModifierGroup>();
            this.Events = new HashSet<Event>();
            this.Courses = new HashSet<Course>();
            this.Batches = new HashSet<Batch>();
            this.CheckIns = new HashSet<CheckIn>();
            this.Options = new HashSet<Setting>();
            this.Staffs = new HashSet<Staff>();
            this.Tables = new HashSet<Table>();
            this.DateConstraints = new HashSet<DateConstraint>();
            this.Printers = new HashSet<Printer>();
            this.Notifications = new HashSet<Notification>();
            this.CashUpDays = new HashSet<CashUpDay>();
            this.StaffAuthenticationKeys = new HashSet<StaffAuthenticationKey>();
            this.Address = new Address();
            this.Settings = new RestaurantSettings();
            this.Position = new LatLongPair();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> RestaurantId { get; set; }
        public string Description { get; set; }
        public int CurrencyId { get; set; }
        public int CountryId { get; set; }
        public string PhoneNumber { get; set; }
        public string PublicEmailAddress { get; set; }
        public string PhoneNumber2 { get; set; }
        public Nullable<int> MenuId { get; set; }
        public bool Enabled { get; set; }
        public string ReceiptFooter { get; set; }
        public string Website { get; set; }
        public string VATNumber { get; set; }
        public Nullable<int> ReceiptResourceId { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public bool EnabledForWaiter { get; set; }
        public Nullable<int> TakeawayPrinterId { get; set; }
        public Nullable<int> BillingPrinterId { get; set; }
        public int TakeawayOffered { get; set; }
    
        public Address Address { get; set; }
        public RestaurantSettings Settings { get; set; }
        public LatLongPair Position { get; set; }
    
        public virtual ICollection<Session> Sessions { get; set; }
        public virtual ICollection<Service> Services { get; set; }
        public virtual ICollection<MenuTag> MenuTags { get; set; }
        public virtual ICollection<MenuItem> MenuItems { get; set; }
        public virtual ICollection<Floor> Floors { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<Restaurant> Restaurants { get; set; }
        public virtual Restaurant HeadOffice { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<Device> Devices { get; set; }
        public virtual ICollection<DeviceRegistrationToken> DeviceRegistrationTokens { get; set; }
        public virtual ICollection<Resource> Resources { get; set; }
        public virtual ICollection<Menu> Menus { get; set; }
        public virtual ICollection<ModifierGroup> ModifierGroups { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<Batch> Batches { get; set; }
        public virtual ICollection<CheckIn> CheckIns { get; set; }
        public virtual Menu TakeawayMenu { get; set; }
        public virtual ICollection<Setting> Options { get; set; }
        public virtual ICollection<Staff> Staffs { get; set; }
        public virtual ICollection<Table> Tables { get; set; }
        public virtual ICollection<DateConstraint> DateConstraints { get; set; }
        public virtual ICollection<Printer> Printers { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual Resource ReceiptResource { get; set; }
        public virtual ICollection<CashUpDay> CashUpDays { get; set; }
        public virtual ICollection<StaffAuthenticationKey> StaffAuthenticationKeys { get; set; }
    }
}
