//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleItem
    {
        public ScheduleItem()
        {
            this.Notifications = new HashSet<Notification>();
        }
    
        public int Id { get; set; }
        public int ServiceId { get; set; }
        public int Delay { get; set; }
        public string Comment { get; set; }
    
        public virtual ICollection<Notification> Notifications { get; set; }
    }
}
