//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatedSession : Session
    {
        public SeatedSession()
        {
            this.Delay = 0;
            this.Tables = new HashSet<Table>();
            this.Diners = new HashSet<Diner>();
        }
    
        public int ServiceId { get; set; }
        public string ChairData { get; set; }
        public int Delay { get; set; }
        public Nullable<double> TipTotal { get; set; }
    
        public virtual ICollection<Table> Tables { get; set; }
        public virtual ICollection<Diner> Diners { get; set; }
        public virtual Service Service { get; set; }
        public virtual Party Party { get; set; }
    }
}
