//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.ScheduleItems = new HashSet<ScheduleItem>();
            this.RecurringScheduleItems = new HashSet<RecurringScheduleItem>();
            this.Courses = new HashSet<Course>();
        }
    
        public int Id { get; set; }
        public int RestaurantId { get; set; }
        public string ServiceName { get; set; }
        public string Notes { get; set; }
        public int MenuId { get; set; }
        public System.DateTime Updated { get; set; }
        public bool Active { get; set; }
        public bool IsTakeaway { get; set; }
        public Nullable<int> MenuId1 { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        public virtual Menu DefaultMenu { get; set; }
        public virtual ICollection<ScheduleItem> ScheduleItems { get; set; }
        public virtual ICollection<RecurringScheduleItem> RecurringScheduleItems { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
        public virtual Menu SelfServiceMenu { get; set; }
    }
}
