//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public Session()
        {
            this.Events = new HashSet<Event>();
            this.NotificationAcks = new HashSet<NotificationAck>();
            this.Orders = new HashSet<Order>();
            this.AdhocNotifications = new HashSet<AdhocNotification>();
            this.Payments = new HashSet<Payment>();
            this.Adjustments = new HashSet<Adjustment>();
        }
    
        public int Id { get; set; }
        public int RestaurantId { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> ClosedTime { get; set; }
        public bool Started { get; set; }
        public double PriceOffset { get; set; }
        public int InstantiatedFromId { get; set; }
        public bool Paid { get; set; }
        public bool RequestedBill { get; set; }
        public double PercentageOffset { get; set; }
        public Nullable<int> CashUpDayId { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        public virtual Customer PrimaryCustomer { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<NotificationAck> NotificationAcks { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<AdhocNotification> AdhocNotifications { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual CashUpDay CashUpDay { get; set; }
        public virtual ICollection<Adjustment> Adjustments { get; set; }
    }
}
