//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public Staff()
        {
            this.Deleted = false;
            this.Roles = new HashSet<Role>();
            this.CashUpDays = new HashSet<CashUpDay>();
            this.StaffAuthenticationKeys = new HashSet<StaffAuthenticationKey>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Pin { get; set; }
        public string Username { get; set; }
        public string Phone { get; set; }
        public string Auth { get; set; }
        public string Salt { get; set; }
        public int RestaurantId { get; set; }
        public bool Deleted { get; set; }
    
        public virtual ICollection<Role> Roles { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        public virtual ICollection<CashUpDay> CashUpDays { get; set; }
        public virtual ICollection<StaffAuthenticationKey> StaffAuthenticationKeys { get; set; }
    }
}
