//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffAuthenticationKey
    {
        public int Id { get; set; }
        public string Key { get; set; }
        public System.DateTime Expires { get; set; }
        public int StaffAuthenticationKeyStaff_StaffAuthenticationKey_Id { get; set; }
        public int Restaurant_Id { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
