//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableLayout
    {
        public TableLayout()
        {
            this.Position = new Position();
        }
    
        public int Id { get; set; }
        public int TableId { get; set; }
        public int LayoutId { get; set; }
    
        public Position Position { get; set; }
    
        public virtual Table Table { get; set; }
    }
}
