//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public Table()
        {
            this.SeatedSessions = new HashSet<SeatedSession>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public short Shape { get; set; }
        public short DefaultCovers { get; set; }
        public int RestaurantId { get; set; }
    
        public virtual ICollection<SeatedSession> SeatedSessions { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
