//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TakeAwaySession : Session
    {
        public TakeAwaySession()
        {
            this.Accepted = true;
            this.Rejected = false;
            this.DeliveryAddress = new Address();
        }
    
        public int TakeAwayTypeId { get; set; }
        public bool Delivery { get; set; }
        public System.DateTime ExpectedTime { get; set; }
        public string Message { get; set; }
        public string Telephone { get; set; }
        public string Name { get; set; }
        public string RejectionNotice { get; set; }
        public bool Accepted { get; set; }
        public bool Rejected { get; set; }
        public bool Deleted { get; set; }
    
        public Address DeliveryAddress { get; set; }
    
        public virtual Diner Diner { get; set; }
    }
}
