//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epicuri.Core.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxType
    {
        public TaxType()
        {
            this.MenuItems = new HashSet<MenuItem>();
            this.Modifiers = new HashSet<Modifier>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public double Rate { get; set; }
        public int CountryId { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<MenuItem> MenuItems { get; set; }
        public virtual ICollection<Modifier> Modifiers { get; set; }
    }
}
